;COMPARE TO STRINGS
ASSUME CS:CODE, DS:DATA
DATA SEGMENT
    STRING1 DB 'Hello',0
    STRING2 DB 'Hello Hi',0
    MSG1 DB 'STRINGS ARE EQUAL$'
    MSG2 DB 'STRINGS ARE NOT EQUAL$'
DATA ENDS
CODE SEGMENT 
    START:
    MOV AX,DATA
    MOV DS,AX
    MOV ES,AX
    
    LEA SI,STRING1
    LEA DI,STRING2
    
    COMPARE_LOOP:
    MOV AL,[SI]
    MOV BL,[DI]
    CMP AL,BL
    JNE NOT_EQUAL
    CMP AL,0H
    JE EQUAL
    INC SI
    INC DI
    JMP COMPARE_LOOP
    
    NOT_EQUAL:
    LEA DX,MSG2
    MOV AH,09H
    INT 21H
    JMP FIN
    
    EQUAL:
    LEA DX,MSG1
    MOV AH,09H
    INT 21H
    
    FIN:
    MOV AH,4CH
    INT 21H
CODE ENDS
END START