ASSUME CS:CODE, DS:DATA
DATA SEGMENT
    DIVIH DW 0000H
    DIVIL DW 0500H
    DIVS DW 0010H
    QUO DW ?
    REM DW ?
DATA ENDS
CODE SEGMENT
    START:
    MOV AX,DATA
    MOV DS, AX
    
    MOV DX,DIVIH
    MOV AX, DIVIL
    DIV DIVS
    MOV QUO, AX
    MOV REM, DX
    
    MOV AH,4CH 
    INT 21H
CODE ENDS
END START    