ASSUME CS:CODE, DS:DATA
DATA SEGMENT
    OP1 DW 6669H
    OP2 DW 9999H
    RES DW ?
    BOR DB 0
DATA ENDS
CODE SEGMENT
START: MOV AX,DATA
    MOV DS, AX
    MOV AX,OP1 
    MOV CL,00H
    SUB AX,OP2
    JNC FIN
    INC CL
    
FIN: MOV RES,AX
    MOV BOR,CL
    MOV AH,4CH
    INT 21H
CODE ENDS
END START 