ASSUME CS:CODE, DS:DATA
DATA SEGMENT
    OP1L DW 6669H
    OP1H DW 1234H
    OP2L DW 9999H 
    OP2H DW 0FFFCH
    RESL DW ?
    RESH DW ?
    BOR DB 0
DATA ENDS
CODE SEGMENT
START: MOV AX,DATA
    MOV DS, AX 
    MOV CL,00H
    MOV AX,OP1L 
    SUB AX,OP2L 
    MOV RESL,AX
    MOV AX,OP1H 
    SBB AX,OP2H
    JNC FIN
    INC CL
    
FIN: MOV RESH,AX
    MOV BOR,CL
    MOV AH,4CH
    INT 21H
CODE ENDS
END START