ASSUME CS:CODE, DS:DATA
DATA SEGMENT
    OP1 DW 1234H
    OP1 DW 5678H
    RES DW ?
    CAR DB 0
DATA ENDS
CODE SEGMENT
START: MOV AX,DATA
    MOV DS, AX
    MOV AX,OP1 
    MOV CL,00
    ADD OP2
    JNC FIN
    INC CL
    MOV CAR,CL
FIN: MOV RES,AX
    MOV AH,4CH
    INT 21H
CODE ENDS
END START  