ASSUME CS:CODE, DS:DATA
DATA SEGMENT
    OP1L DW 6669H
    OP1H DW 1234H
    OP2L DW 9999H 
    OP2H DW FFFCH
    RES1 DW ?
    RES2 DW ?
    CAR DB 0
DATA ENDS
CODE SEGMENT
START: MOV AX,DATA
    MOV DS, AX
    MOV AX,OP1 
    MOV CL,00H
    SUB AX,OP2
    JNC FIN
    INC CL
    
FIN: MOV RES,AX
    MOV BOR,CL
    MOV AH,4CH
    INT 21H
CODE ENDS
END START